name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Use a general 3.x version
      - name: Install deps & run tests
        run: |
          pip install pytest kafka-python psycopg2-binary
          # Adjust PYTHONPATH if tests are not directly runnable from root
          # export PYTHONPATH=${PYTHONPATH}:. 
          pytest --maxfail=1 --disable-warnings -q tests/
